on: 
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [homework-update]

name: Build and deploy GH Pages

jobs:
  discover-labs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Clone homeworks repository
        run: |
          git clone --depth 1 https://github.com/ap-1/homeworks.git homeworks-temp

      - name: Discover labs
        id: set-matrix
        run: |
          chmod +x .github/scripts/discover-labs.sh
          matrix=$(.github/scripts/discover-labs.sh)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build-labs:
    needs: discover-labs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.discover-labs.outputs.matrix)}}
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Clone homeworks repository
        run: |
          git clone --depth 1 https://github.com/ap-1/homeworks.git homeworks-temp

      - name: Get lab content hash
        id: lab-hash
        run: |
          lab_hash=$(find homeworks-temp/${{ matrix.week }}/${{ matrix.lab }} -type f \( -name "*.rs" -o -name "*.toml" -o -name "*.md" \) -exec sha256sum {} \; 2>/dev/null | sort | sha256sum | cut -d' ' -f1)
          echo "hash=$lab_hash" >> $GITHUB_OUTPUT

      - name: Cache lab artifacts
        uses: actions/cache@v4
        with:
          path: hw/${{ matrix.lab }}
          key: lab-${{ matrix.lab }}-${{ steps.lab-hash.outputs.hash }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build lab documentation
        run: |
          chmod +x .github/scripts/build-lab.sh
          .github/scripts/build-lab.sh ${{ matrix.week }} ${{ matrix.lab }}

      - name: Upload lab artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.lab }}
          path: hw/${{ matrix.lab }}

  build-website:
    needs: build-labs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: Download all lab artifacts
        uses: actions/download-artifact@v5
        with:
          path: hw

      - name: Reorganize artifacts
        run: |
          # Move artifacts from nested structure to flat structure
          find hw -name "*.zip" -o -name "doc" -type d | while read item; do
            parent_dir=$(dirname "$item")
            lab_name=$(basename "$parent_dir")
            if [ "$parent_dir" != "hw/$lab_name" ]; then
              mkdir -p "hw/$lab_name"
              mv "$item" "hw/$lab_name/"
            fi
          done

      - name: Build website
        run: |
          npm install
          npm run-script build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
